/*--------------------------------------------------------------------------------------------------
This Program was generated by Alberto Bobadilla in 2014
--------------------------------------------------------------------------------------------------*/
#ifndef _BASE_H
#define _BASE_H

#include <cstring>
#include <iostream>

class Base
{
public:
    /** Constructor */
    Base();
 
    /** Copy Constructor */
    Base (const Base& other);

	/** Copy Assignment Operator */
    Base& operator= (const Base& other);
 
    /** Destructor */
    ~Base();

	/**function*/
	void Method();

	/** FriendFunction*/
	friend void PrivateAccessor(Base &other);
	//friend void PrivateAccessor(Base &other)
	//{
	//	std::cout << __FUNCTION__ << std::endl;
	//	std::cout << "Value of Data: " << other.data << std::endl << std::endl;
	//}

	/** FriendClass*/
	friend class MyFriend;
 
private:
    int data;
};

#endif //_Base_H