/*--------------------------------------------------------------------------------------------------
This Program was generated by Alberto Bobadilla in 2013
It tries to explain the use of Friend
--------------------------------------------------------------------------------------------------*/
#include "Base.h"
#include "MyFriend.h"

int main()
{
	//Objects
	Base b;
	MyFriend myFriend;

	//Method inside b
	b.Method();
	
	//method outside b
	PrivateAccessor(b);

	//Method in MyFriend with all access
	myFriend.Method();

	//Ending the program
	std::cout << "\nPress enter to finish";
	getchar();
	return 0;
}