/*--------------------------------------------------------------------------------------------------
This Program was generated by Alberto Bobadilla in 2014
--------------------------------------------------------------------------------------------------*/
#ifndef _MYFRIEND_H
#define _MYFRIEND_H

#include "Base.h"
 
class MyFriend
{
public:
	Base var;
    /** Constructor */
    MyFriend();
 
    /** Copy Constructor */
    MyFriend (const MyFriend& other);

	/** Copy Assignment Operator */
    MyFriend& operator= (const MyFriend& other);
 
    /** Destructor */
    ~MyFriend();

	/** Method */
	void Method(void);
};

#endif //_Base_H